### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by sunnythepatel** [trntv/kubernetes-dashboard-desktop-app#7]
I don't think the readme is properly explained as after installation using homebrew I am getting a lot of errors. Can you please let me know what to do next to fix this issue.
![image](https://user-images.githubusercontent.com/24850477/115949649-d0c0e500-a519-11eb-8eb5-2864c7a81a80.png)

**Comment by sunnythepatel** [comment]
I think I got it now but it's better to mention that you need to have a cluster running in the background in the first place

**Comment by trntv** [comment]
You don't have to :-) 
It will connect to cluster that is used as your ``current-context`` in kube config file
